### ISSUE TITLE
Correct way of loading plugins

### ISSUE THREAD

**Issue by heuels** [easeway/js-plugins#3]
Hi.  
I am having a little trouble understanding how this package works. Currently I am able to load a plugin, but I can't call any of its methods. And to make it work I commented out lines [55-57](https://github.com/easeway/js-plugins/blob/master/lib/Plugins.js#L55) of `Plugins.js`. Clearly, I am doing something wrong. May I ask you to take a quick look at my code?  

This is what I have in my **plugin**:  

**package.json**

``` javascript
{
  "name": "myAppPlugin-test1",
  "version": "0.1.0",
  "description": "Test plugin",
  "main": "myAppPlugin-test1.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 0"
  },
  "license": "MIT",
  "extensions": {
    "myAppName:test": {
      "myAppPlugin-test1" : "myAppPlugin-test1.js"
      }
  }
}
```

**myAppName-test1.js**

``` javascript
Test.prototype.sayHello = function (sayHelloWorld, cb) {
  cb(this.testvalue + ' ' + sayHelloWorld.toString());
}

function Test () {
  this.testvalue = 'hello,world!';
  return this;
}

module.exports = Test;
```

And this is what I have in my **host**:

``` javascript
// An object to act as host.
function HostObj(data) {
  return this;
}
var testobj = new HostObj();

var Plugins = require('js-plugins');
var pluginManager = new Plugins();

pluginManager.scan();
pluginManager.connect(testobj, 'myAppName:test', {'multi': true}, function(err, extensions, names) {
  console.log('err', err);  // null
  console.log('extensions', extensions);  // [{ ... }]
  console.log('names', names);  // [ 'myAppPlugin-test1' ]
}
```

**Comment by mbaynton** [comment]
Yes, a complete example including calling a method on a loaded plugin would be helpful.

**Comment by mbaynton** [comment]
So I think where @heuels and I are getting tripped up is that js-plugins seems to be expecting there to be a function provided by the npm module containing the plugin as a "factory" for the module. But I don't want / need my npm module to be anything other than an npm module. Just one that also has some extra tags in package.json so I can go scan for all available plugins of a type.

If you do 
**package.json**

``` json
{
  "name": "module-offering-plugin",
  "version": "0.0.1",
  "extensions": {
    "somehostapp:plugintype": {
      "name-of-plugin": {
        "module": "./codeFile",
        "object": "instantiatePlugin"
      }
    }
```

}`

**codeFile.js**

``` javascript
exports.thing1 = "la la la";
exports.initiatePlugin = function() { return exports; }
```

...then it works, but clearly this isn't the intended pattern.

I'm pretty new to node/npm and am stumped about what the "right" way to write a js-plugin compatible npm module is.

**Comment by orlade** [comment]
I agree, the documentation alone is not quite sufficient to feel comfortable using js-plugins, which is a shame because after exploring the test cases and hacking around with it for a while, I love it!

I made [an example project called MultiGreet](https://github.com/orlade/js-plugins-example), which prints a greeting to audience members defined by plugins. It's not perfect, but hopefully it can help others get started with js-plugins.

**Comment by davisjohndavis3** [comment]
I am new to Typescript. How to change the plugin [index and package file ] into typescript and how to handle it in the host application. @heuels , @orlade , @easeway . What i did is


**index.d.ts** file

declare function hai (data: any, host: any, options: any){
  return {
    hello: function(){
      return "happy scriptring";
    }
  };
}

export = hai;

But index.d.ts file shows error " [ts] An implementation cannot be declared in ambient contexts.".
And i placed the both file in a folder under .node_modules

**package.json** file

{
    "name": "js-plugins-example-people",
    "version": "0.0.1",
    "extensions": {
      "sample:plugin": {
        "john": "./"
      }
    }
  }

**host.js** file

var hostObj = '';

// pluginManager.scanSubdirs([__dirname]);
pluginManager.scan();
pluginManager.connect(hostObj, 'sample:plugin', {multi: true}, function (err: any, outputs: any, names: any) {
   outputs.map(function(values: any){
     console.log(values.hello());
   })
   console.log("Hello World");
});

**Comment by davisjohndavis3** [comment]
We need to add "typings" package in application side. And add things below in your plugin side.

    {
    "name": "sampleplugin",
    "version": "0.0.1",
    "typings": [
        "./globals.ts"
    ],
    "extensions": {
        "default": {
            "default": "./globals.ts"
        }
     }
    }
